import { describe, it, expect, vi, beforeEach } from "vitest";
import path from "node:path";

vi.mock("node:fs", () => {
  const store = new Map<string, string>();
  return {
    default: {
      existsSync: vi.fn((p: string) => store.has(p)),
      readFileSync: vi.fn((p: string) => {
        if (!store.has(p)) throw new Error("ENOENT");
        return store.get(p);
      }),
      writeFileSync: vi.fn((p: string, data: string) => {
        store.set(p, data);
      }),
      mkdirSync: vi.fn(),
      __store: store,
    },
  };
});

import fs from "node:fs";
import {
  isProfileDecorated,
  decorateEClawProfile,
  ensureProfileCleanExit,
} from "./chrome.profile-decoration.js";

const store = (fs as unknown as { __store: Map<string, string> }).__store;

beforeEach(() => {
  store.clear();
  vi.clearAllMocks();
});

// ---------------------------------------------------------------------------
// decorateEClawProfile
// ---------------------------------------------------------------------------

describe("decorateEClawProfile", () => {
  const userDataDir = "/tmp/chrome-profile";
  const localStatePath = path.join(userDataDir, "Local State");
  const prefsPath = path.join(userDataDir, "Default", "Preferences");

  it("writes Local State and Preferences with default name and color", () => {
    decorateEClawProfile(userDataDir);

    expect(fs.writeFileSync).toHaveBeenCalled();
    expect(store.has(localStatePath)).toBe(true);
    expect(store.has(prefsPath)).toBe(true);

    const localState = JSON.parse(store.get(localStatePath)!);
    expect(localState.profile.info_cache.Default.name).toBe("eclaw");
    expect(localState.profile.info_cache.Default.profile_color).toBe("#FF4500");
  });

  it("uses custom name and color when provided", () => {
    decorateEClawProfile(userDataDir, { name: "test-bot", color: "#00FF00" });

    const localState = JSON.parse(store.get(localStatePath)!);
    expect(localState.profile.info_cache.Default.name).toBe("test-bot");
    expect(localState.profile.info_cache.Default.profile_color).toBe("#00FF00");

    const prefs = JSON.parse(store.get(prefsPath)!);
    expect(prefs.profile.name).toBe("test-bot");
  });

  it("writes color int fields for valid hex color", () => {
    decorateEClawProfile(userDataDir);

    const localState = JSON.parse(store.get(localStatePath)!);
    expect(typeof localState.profile.info_cache.Default.profile_color_seed).toBe("number");

    const prefs = JSON.parse(store.get(prefsPath)!);
    expect(typeof prefs.autogenerated.theme.color).toBe("number");
    expect(typeof prefs.browser.theme.user_color2).toBe("number");
  });

  it("preserves existing Local State data", () => {
    store.set(localStatePath, JSON.stringify({ existing_key: "preserved" }));
    (fs.existsSync as ReturnType<typeof vi.fn>).mockImplementation((p: string) => store.has(p));

    decorateEClawProfile(userDataDir);

    const localState = JSON.parse(store.get(localStatePath)!);
    expect(localState.existing_key).toBe("preserved");
    expect(localState.profile.info_cache.Default.name).toBe("eclaw");
  });

  it("writes marker file", () => {
    decorateEClawProfile(userDataDir);

    const markerPath = path.join(userDataDir, ".eclaw-profile-decorated");
    expect(store.has(markerPath)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// isProfileDecorated
// ---------------------------------------------------------------------------

describe("isProfileDecorated", () => {
  const userDataDir = "/tmp/chrome-profile";
  const localStatePath = path.join(userDataDir, "Local State");
  const prefsPath = path.join(userDataDir, "Default", "Preferences");

  function setupDecorated(name: string, colorHex: string) {
    decorateEClawProfile(userDataDir, { name, color: colorHex });
    // Reset existsSync to use the store
    (fs.existsSync as ReturnType<typeof vi.fn>).mockImplementation((p: string) => store.has(p));
  }

  it("returns true when Local State and Preferences match", () => {
    setupDecorated("eclaw", "#FF4500");
    expect(isProfileDecorated(userDataDir, "eclaw", "#FF4500")).toBe(true);
  });

  it("returns false when name differs", () => {
    setupDecorated("eclaw", "#FF4500");
    expect(isProfileDecorated(userDataDir, "different-name", "#FF4500")).toBe(false);
  });

  it("returns false when color differs", () => {
    setupDecorated("eclaw", "#FF4500");
    expect(isProfileDecorated(userDataDir, "eclaw", "#00FF00")).toBe(false);
  });

  it("handles missing files gracefully", () => {
    (fs.existsSync as ReturnType<typeof vi.fn>).mockReturnValue(false);
    // With no files, color int check returns false
    expect(isProfileDecorated(userDataDir, "eclaw", "#FF4500")).toBe(false);
  });

  it("returns nameOk for invalid hex color (non #RRGGBB)", () => {
    setupDecorated("eclaw", "#FF4500");
    // Invalid hex means desiredColorInt is null, so only name check matters
    expect(isProfileDecorated(userDataDir, "eclaw", "not-a-color")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ensureProfileCleanExit
// ---------------------------------------------------------------------------

describe("ensureProfileCleanExit", () => {
  const userDataDir = "/tmp/chrome-profile";
  const prefsPath = path.join(userDataDir, "Default", "Preferences");

  it("sets exit_type and exited_cleanly in Preferences", () => {
    ensureProfileCleanExit(userDataDir);

    const prefs = JSON.parse(store.get(prefsPath)!);
    expect(prefs.exit_type).toBe("Normal");
    expect(prefs.exited_cleanly).toBe(true);
  });

  it("preserves existing preferences data", () => {
    store.set(prefsPath, JSON.stringify({ profile: { name: "test" } }));
    (fs.existsSync as ReturnType<typeof vi.fn>).mockImplementation((p: string) => store.has(p));

    ensureProfileCleanExit(userDataDir);

    const prefs = JSON.parse(store.get(prefsPath)!);
    expect(prefs.profile.name).toBe("test");
    expect(prefs.exit_type).toBe("Normal");
  });
});

// ---------------------------------------------------------------------------
// parseHexRgbToSignedArgbInt (tested via public API)
// ---------------------------------------------------------------------------

describe("parseHexRgbToSignedArgbInt (via decorateEClawProfile)", () => {
  const userDataDir = "/tmp/chrome-profile";
  const localStatePath = path.join(userDataDir, "Local State");

  it("#FF4500 produces correct signed ARGB int", () => {
    decorateEClawProfile(userDataDir, { color: "#FF4500" });
    const localState = JSON.parse(store.get(localStatePath)!);
    const colorInt = localState.profile.info_cache.Default.profile_color_seed;
    // 0xFFFF4500 as unsigned = 4294934784, as signed = -32512
    expect(typeof colorInt).toBe("number");
    expect(colorInt).toBeLessThan(0); // high bit set → negative signed int
  });

  it("#000000 produces correct signed ARGB int", () => {
    decorateEClawProfile(userDataDir, { color: "#000000" });
    const localState = JSON.parse(store.get(localStatePath)!);
    const colorInt = localState.profile.info_cache.Default.profile_color_seed;
    // 0xFF000000 = 4278190080 → signed = -16777216
    expect(colorInt).toBe(-16777216);
  });

  it("#FFFFFF produces correct signed ARGB int", () => {
    decorateEClawProfile(userDataDir, { color: "#FFFFFF" });
    const localState = JSON.parse(store.get(localStatePath)!);
    const colorInt = localState.profile.info_cache.Default.profile_color_seed;
    // 0xFFFFFFFF = 4294967295 → signed = -1
    expect(colorInt).toBe(-1);
  });

  it("invalid hex does not write color int fields", () => {
    decorateEClawProfile(userDataDir, { color: "invalid" });
    const localState = JSON.parse(store.get(localStatePath)!);
    expect(localState.profile.info_cache.Default.profile_color_seed).toBeUndefined();
  });
});
